import { mockJobs } from "./mock-jobs";
import type { Job } from "./types";

/**
 * Mock listings aimed at the AI-adjacent directions, including bilingual
 * listings and deliberately poor matches so downgrade logic is visible.
 * Real sources can replace this array later — the shape is source-agnostic.
 */
export const careerJobs: Job[] = [
  {
    id: "shiro-ai-ecommerce-operations",
    title: "AI E-commerce Operations Specialist",
    titleOriginal: "AI电商运营专员",
    company: "Shiro Global",
    location: "Remote (China / APAC)",
    workMode: "remote",
    employmentType: "fulltime",
    salaryMin: 90000,
    salaryMax: 130000,
    skills: [
      "Cross-border E-commerce Operations",
      "Listing Optimization",
      "Advertising Operations",
      "AI Product Image Generation",
      "Prompt Engineering",
    ],
    seniority: "mid",
    postedDaysAgo: 0,
    summary:
      "Run cross-border listings with an AI-first toolchain: generated imagery, assisted copy, automated ad reporting.",
    summaryOriginal:
      "以AI工具为核心运营跨境店铺：AI生成图、辅助文案、广告数据自动化报表。",
    responsibilities: [
      "Own listing quality and AI-generated creative for 200+ SKUs",
      "Run assisted keyword and ad iteration weekly",
      "Document which AI workflows actually move conversion",
    ],
    industry: "Cross-border e-commerce",
    careerDirection: "ai-ecommerce",
    aiRelevance: 80,
    growthPotential: 72,
    portfolioValue: 65,
    repetitiveWorkRisk: 30,
    overtimeRisk: 25,
    language: "zh",
    source: "mock",
  },
  {
    id: "beacon-ai-product-research",
    title: "AI Product Research Associate",
    company: "Beacon Labs",
    location: "Remote (Global)",
    workMode: "remote",
    employmentType: "fulltime",
    salaryMin: 95000,
    salaryMax: 135000,
    skills: [
      "Overseas Market Research",
      "Competitor Analysis",
      "Product Development",
      "Data Analysis",
      "Product Management",
    ],
    seniority: "mid",
    postedDaysAgo: 1,
    summary:
      "Research demand and competitors for an AI product team, and turn findings into feature proposals.",
    responsibilities: [
      "Run market and competitor research cycles",
      "Translate findings into scoped feature proposals",
      "Sit with designers and engineers on discovery",
    ],
    industry: "AI SaaS",
    careerDirection: "ai-product",
    aiRelevance: 88,
    growthPotential: 90,
    portfolioValue: 75,
    repetitiveWorkRisk: 15,
    overtimeRisk: 30,
    source: "mock",
  },
  {
    id: "yuanli-ai-visual-designer",
    title: "AI Visual Creation Specialist",
    titleOriginal: "AI视觉创意专员",
    company: "Yuanli Studio",
    location: "Hybrid — Shenzhen",
    workMode: "hybrid",
    employmentType: "fulltime",
    salaryMin: 70000,
    salaryMax: 100000,
    skills: ["AI Product Image Generation", "Photoshop", "Prompt Engineering", "Short Video Editing"],
    seniority: "mid",
    postedDaysAgo: 2,
    summary:
      "Produce commercial visuals for consumer brands using AI generation plus hands-on retouching.",
    summaryOriginal: "使用AI生成结合手工精修，为消费品牌产出商业视觉素材。",
    responsibilities: [
      "Build AI visual sets for campaigns and listings",
      "Keep output consistent with each brand's guidelines",
      "Maintain a reusable prompt and asset library",
    ],
    industry: "Creative studio",
    careerDirection: "ai-visual",
    aiRelevance: 78,
    growthPotential: 68,
    portfolioValue: 85,
    repetitiveWorkRisk: 35,
    overtimeRisk: 40,
    language: "zh",
    source: "mock",
  },
  {
    id: "loop-ai-ops-analyst",
    title: "Operations Automation Analyst",
    company: "Loop Commerce",
    location: "Remote (EU/APAC)",
    workMode: "remote",
    employmentType: "fulltime",
    salaryMin: 85000,
    salaryMax: 118000,
    skills: [
      "E-commerce Operations",
      "Data Monitoring",
      "Automation",
      "Basic Programming",
      "Inventory / Supply Chain Coordination",
    ],
    seniority: "mid",
    postedDaysAgo: 1,
    summary:
      "Replace manual operations reporting with automated pipelines and keep inventory signals trustworthy.",
    responsibilities: [
      "Automate recurring ops and inventory reports",
      "Instrument alerts for stock and rating risk",
      "Train the ops team on the new workflows",
    ],
    industry: "Retail operations",
    careerDirection: "ai-operations",
    aiRelevance: 62,
    growthPotential: 74,
    portfolioValue: 60,
    repetitiveWorkRisk: 30,
    overtimeRisk: 25,
    source: "mock",
  },
  {
    id: "kanmei-content-operations",
    title: "Overseas Content Operations",
    titleOriginal: "海外内容运营",
    company: "Kanmei",
    location: "Remote (China)",
    workMode: "remote",
    employmentType: "fulltime",
    salaryMin: 60000,
    salaryMax: 88000,
    skills: ["Content Operations", "Short Video Editing", "Copywriting", "Overseas Market Research"],
    seniority: "mid",
    postedDaysAgo: 3,
    summary:
      "Plan and ship AI-assisted short video and copy for overseas channels, with weekly performance review.",
    summaryOriginal: "策划并产出AI辅助的海外短视频与文案，按周复盘数据。",
    responsibilities: [
      "Own the weekly content calendar for two channels",
      "Use AI drafting, then edit for tone and accuracy",
      "Report on retention and click-through",
    ],
    industry: "Consumer brand",
    careerDirection: "ai-content",
    aiRelevance: 66,
    growthPotential: 66,
    portfolioValue: 78,
    repetitiveWorkRisk: 40,
    overtimeRisk: 45,
    language: "zh",
    source: "mock",
  },
  {
    id: "pivot-ai-prompt-project",
    title: "AI Listing Copy Project (Part-time)",
    company: "Pivot Collective",
    location: "Remote",
    workMode: "remote",
    employmentType: "parttime",
    salaryMin: 6000,
    salaryMax: 9000,
    salaryNote: "Project fee, ~10 hrs/week for 6 weeks",
    skills: ["Prompt Engineering", "Listing Optimization", "AI Product Image Generation"],
    seniority: "mid",
    postedDaysAgo: 0,
    summary:
      "Build a reusable AI prompt and copy system for a small brand's 60-SKU catalogue.",
    responsibilities: [
      "Design the prompt library and tone rules",
      "Ship rewritten copy for 60 listings",
      "Hand over documentation the team can run without you",
    ],
    industry: "Consumer brand",
    careerDirection: "ai-ecommerce",
    aiRelevance: 82,
    growthPotential: 60,
    portfolioValue: 90,
    repetitiveWorkRisk: 25,
    overtimeRisk: 10,
    source: "mock",
  },
  {
    id: "atlas-ai-research-freelance",
    title: "Market Research for AI Tool Launch (Part-time)",
    company: "Atlas Ventures",
    location: "Remote (Global)",
    workMode: "remote",
    employmentType: "parttime",
    salaryMin: 4000,
    salaryMax: 7000,
    salaryNote: "Fixed fee, 4-week engagement",
    skills: ["Overseas Market Research", "Competitor Analysis", "Data Analysis"],
    seniority: "mid",
    postedDaysAgo: 1,
    summary:
      "Research the buyer landscape for an AI research tool entering Southeast Asia and write the positioning brief.",
    responsibilities: [
      "Map competitors and pricing",
      "Interview eight target users",
      "Deliver a positioning brief the founders can act on",
    ],
    industry: "AI SaaS",
    careerDirection: "ai-product",
    aiRelevance: 80,
    growthPotential: 70,
    portfolioValue: 88,
    repetitiveWorkRisk: 15,
    overtimeRisk: 15,
    source: "mock",
  },
  {
    id: "brightpath-video-parttime",
    title: "AI Short Video Editing (Part-time)",
    titleOriginal: "AI短视频剪辑（兼职）",
    company: "Brightpath Media",
    location: "Remote (China)",
    workMode: "remote",
    employmentType: "parttime",
    salaryMin: 3000,
    salaryMax: 5000,
    salaryNote: "Per-batch pay, flexible hours",
    skills: ["Short Video Editing", "AI Product Image Generation", "Content Operations"],
    seniority: "mid",
    postedDaysAgo: 2,
    summary:
      "Cut AI-assisted product videos in weekly batches for overseas channels.",
    summaryOriginal: "为海外渠道按周批量剪辑AI辅助的产品短视频。",
    responsibilities: [
      "Produce 6-8 short videos per week",
      "Follow the channel's format and hook rules",
      "Suggest creative variants to test",
    ],
    industry: "Media",
    careerDirection: "ai-content",
    aiRelevance: 58,
    growthPotential: 52,
    portfolioValue: 72,
    repetitiveWorkRisk: 55,
    overtimeRisk: 15,
    language: "zh",
    source: "mock",
  },
  {
    id: "dataflow-entry-parttime",
    title: "Product Data Entry (Part-time)",
    titleOriginal: "产品数据录入（兼职）",
    company: "Dataflow Services",
    location: "Remote",
    workMode: "remote",
    employmentType: "parttime",
    salaryMin: 5000,
    salaryMax: 8000,
    salaryNote: "Hourly, steady volume",
    skills: ["Data Entry", "E-commerce Operations"],
    seniority: "mid",
    postedDaysAgo: 1,
    summary:
      "Enter and verify product attribute data into a catalogue system from supplier sheets.",
    summaryOriginal: "根据供应商表格将产品属性数据录入并核对到系统。",
    responsibilities: [
      "Enter attributes for assigned SKU batches",
      "Verify against supplier sheets",
      "Flag mismatches to the coordinator",
    ],
    industry: "Data services",
    careerDirection: "explore",
    aiRelevance: 10,
    growthPotential: 15,
    portfolioValue: 10,
    repetitiveWorkRisk: 90,
    overtimeRisk: 30,
    negativeTags: ["data_entry", "repetitive", "no_growth"],
    language: "zh",
    source: "mock",
  },
  {
    id: "vantage-b2b-sales",
    title: "B2B Sales Representative",
    titleOriginal: "B2B销售代表",
    company: "Vantage Trade",
    location: "On-site — Guangzhou",
    workMode: "onsite",
    employmentType: "fulltime",
    salaryMin: 55000,
    salaryMax: 120000,
    salaryNote: "Base plus commission",
    skills: ["Sales", "Cross-border E-commerce Operations", "Customer Service"],
    seniority: "mid",
    postedDaysAgo: 2,
    summary:
      "Cold outreach and closing for a cross-border trading company, with monthly quota.",
    summaryOriginal: "跨境贸易公司电话与线索开发，承担月度业绩指标。",
    responsibilities: [
      "Hit a monthly new-client quota",
      "Handle client complaints and follow-ups",
      "Attend evening calls with overseas buyers",
    ],
    industry: "Trading",
    careerDirection: "explore",
    aiRelevance: 12,
    growthPotential: 30,
    portfolioValue: 20,
    repetitiveWorkRisk: 60,
    overtimeRisk: 80,
    negativeTags: ["pure_sales", "customer_service", "unpaid_overtime"],
    language: "zh",
    source: "mock",
  },
];

/** Sensible defaults so the original mock listings work with the new model. */
function withDefaults(job: Job): Job {
  return {
    employmentType: "fulltime",
    aiRelevance: 35,
    growthPotential: 55,
    portfolioValue: 45,
    repetitiveWorkRisk: 30,
    overtimeRisk: 30,
    careerDirection: "explore",
    industry: "Product & design",
    source: "mock",
    language: "en",
    ...job,
  };
}

/** Every listing in the workspace: new career-track jobs plus the originals. */
export const allJobs: Job[] = [...careerJobs.map(withDefaults), ...mockJobs.map(withDefaults)];
