import { conceptKey } from "./concepts";
import type { CareerDirection, CareerProfile } from "./career-types";

/**
 * Concept normalization lives in ./concepts (canonical bilingual taxonomy).
 * Re-exported here so existing call sites keep working.
 */
export function normalizeConcept(term: string) {
  return conceptKey(term);
}

export { sameConcept } from "./concepts";

export const defaultCareerProfile: CareerProfile = {
  basics: {
    education: "Associate degree",
    yearsExperience: 1,
    careerStage: "Early-mid career, changing direction",
    preferredLocations: ["Shenzhen", "Huiyang", "Zhuhai"],
    relocation: "Open to relocation for the right direction",
    workMode: "any",
    languages: ["Chinese (native)", "English (working)"],
  },
  skills: [
    {
      id: "cross-border",
      name: "Cross-border E-commerce Operations",
      nameOriginal: "跨境电商运营",
      level: "advanced",
      evidence: "Ran a TEMU store end to end, 300+ SKUs",
      years: 4,
      confidence: 5,
    },
    {
      id: "market-research",
      name: "Overseas Market Research",
      nameOriginal: "海外市场研究",
      level: "proficient",
      evidence: "Category and demand research for US/EU buyers",
      years: 3,
      confidence: 4,
    },
    {
      id: "product-selection",
      name: "Product Selection",
      nameOriginal: "选品",
      level: "advanced",
      evidence: "Selected and launched winning SKUs each season",
      years: 4,
      confidence: 5,
    },
    {
      id: "product-development",
      name: "Product Development",
      nameOriginal: "产品开发",
      level: "proficient",
      evidence: "Worked with factories on samples and revisions",
      years: 3,
      confidence: 4,
    },
    {
      id: "competitor-analysis",
      name: "Competitor Analysis",
      nameOriginal: "竞品分析",
      level: "proficient",
      evidence: "Priced and positioned against category leaders",
      years: 3,
      confidence: 4,
    },
    {
      id: "listing-optimization",
      name: "Listing Optimization",
      nameOriginal: "Listing优化",
      level: "advanced",
      evidence: "Rewrote titles/images, lifted conversion on core SKUs",
      years: 3,
      confidence: 4,
    },
    {
      id: "ecommerce-operations",
      name: "E-commerce Operations",
      nameOriginal: "电商运营",
      level: "advanced",
      evidence: "Daily average 800+ orders on TEMU",
      years: 4,
      confidence: 5,
    },
    {
      id: "advertising",
      name: "Advertising Operations",
      nameOriginal: "广告投放",
      level: "working",
      evidence: "Improved CTR on some campaigns by 10%",
      years: 2,
      confidence: 3,
    },
    {
      id: "data-monitoring",
      name: "Data Monitoring",
      nameOriginal: "数据监控",
      level: "proficient",
      evidence: "Daily sales, ad and rating dashboards",
      years: 3,
      confidence: 4,
    },
    {
      id: "supply-chain",
      name: "Inventory / Supply Chain Coordination",
      nameOriginal: "库存与供应链协调",
      level: "proficient",
      evidence: "Cleared 20+ slow-moving products",
      years: 3,
      confidence: 4,
    },
    {
      id: "ai-images",
      name: "AI Product Image Generation",
      nameOriginal: "AI产品图生成",
      level: "working",
      evidence: "Generated listing imagery with AI tools",
      years: 1,
      confidence: 3,
    },
    {
      id: "photoshop",
      name: "Photoshop",
      level: "working",
      evidence: "Retouched and composed listing images",
      years: 3,
      confidence: 3,
    },
    {
      id: "video",
      name: "Short Video Editing",
      nameOriginal: "短视频剪辑",
      level: "working",
      evidence: "Produced product videos for listings and ads",
      years: 2,
      confidence: 3,
    },
    {
      id: "programming",
      name: "Basic Programming",
      nameOriginal: "基础编程",
      level: "learning",
      evidence: "Scripts and small automations, still learning",
      years: 1,
      confidence: 2,
    },
  ],
  evidence: [
    {
      id: "ev-sku",
      label: "Managed 300+ SKUs",
      detail: "Across selection, listing and restock cycles.",
    },
    {
      id: "ev-slow",
      label: "Cleared 20+ slow-moving products",
      detail: "Bundling, pricing and ad adjustments.",
    },
    {
      id: "ev-ctr",
      label: "Improved some advertising CTR by 10%",
      detail: "Creative and keyword iteration on selected campaigns.",
    },
    {
      id: "ev-rating",
      label: "Maintained >90% positive rating",
      detail: "Quality control plus faster issue resolution.",
    },
    {
      id: "ev-orders",
      label: "TEMU store daily average 800+ orders",
      detail: "Sustained over the peak season.",
    },
    {
      id: "ev-rank",
      label: "Store consistently in category Top 15",
      detail: "Ranking held across multiple months.",
    },
  ],
  workContent: { creativity: 5, communication: 3, analysis: 4, execution: 4 },
  priorities: {
    growth: 5,
    industryOutlook: 5,
    transferableSkills: 5,
    salary: 3,
    workingHours: 3,
    stability: 2,
  },
  workStyle: { remote: 5, hybrid: 4, onsite: 2 },
  otherPreferences: [
    { id: "pref-guidance", label: "Wants some initial guidance", enabled: true },
    { id: "pref-autonomy", label: "Wants increasing autonomy", enabled: true },
    { id: "pref-mix", label: "Comfortable with independent and collaborative work", enabled: true },
    { id: "pref-learn", label: "High willingness to learn", enabled: true },
    { id: "pref-ai", label: "Strong interest in AI", enabled: true },
  ],
  dealBreakers: [
    { id: "db-sales", label: "Pure sales", tag: "pure_sales", severity: "severe" },
    { id: "db-cs", label: "Customer service", tag: "customer_service", severity: "severe" },
    { id: "db-entry", label: "Pure data entry", tag: "data_entry", severity: "severe" },
    { id: "db-rep", label: "Highly repetitive work", tag: "repetitive", severity: "moderate" },
    { id: "db-ot", label: "Meaningless overtime", tag: "unpaid_overtime", severity: "moderate" },
    { id: "db-growth", label: "No meaningful growth", tag: "no_growth", severity: "moderate" },
  ],
  learning: {
    willingness: 5,
    interestedSkills: [
      "AI product workflows",
      "Prompt engineering",
      "Automation",
      "Data analysis",
      "AI visual creation",
    ],
    ai: 5,
    programming: 3,
    automation: 4,
    product: 4,
    content: 4,
    visual: 5,
    uncertaintyTolerance: 4,
  },
};

export const careerDirections: CareerDirection[] = [
  {
    id: "ai-ecommerce",
    name: "AI × E-commerce",
    nameOriginal: "AI × 跨境电商",
    blurb: "Use AI tools inside selection, listing and advertising work you already know.",
    coreSkills: [
      "Cross-border E-commerce Operations",
      "Product Selection",
      "Listing Optimization",
      "E-commerce Operations",
      "Advertising Operations",
    ],
    transferableSkills: ["Data Monitoring", "Competitor Analysis", "AI Product Image Generation"],
    learnable: ["AI-assisted listing generation", "Prompt engineering", "Ad automation"],
    aiRelevance: 75,
    growthPotential: 70,
    marketOpportunity: 80,
    interestKeys: ["ai", "automation"],
    nextStep:
      "Rebuild one past listing end-to-end with AI tools and record the before/after numbers.",
  },
  {
    id: "ai-product",
    name: "AI × Product",
    nameOriginal: "AI × 产品",
    blurb: "Move from running a store to shaping AI-assisted products and research.",
    coreSkills: ["Overseas Market Research", "Product Development", "Competitor Analysis"],
    transferableSkills: ["Data Monitoring", "Product Selection", "Basic Programming"],
    learnable: ["Product discovery frameworks", "PRD writing", "AI feature scoping"],
    aiRelevance: 85,
    growthPotential: 90,
    marketOpportunity: 75,
    interestKeys: ["product", "ai", "programming"],
    nextStep: "Write one product teardown of an AI tool you use, with a proposed next feature.",
  },
  {
    id: "ai-content",
    name: "AI × Content / Creative",
    nameOriginal: "AI × 内容创意",
    blurb: "Turn product storytelling and short video into an AI-assisted content practice.",
    coreSkills: ["Short Video Editing", "Listing Optimization"],
    transferableSkills: [
      "Overseas Market Research",
      "Competitor Analysis",
      "AI Product Image Generation",
    ],
    learnable: ["AI scriptwriting", "Content systems", "Channel analytics"],
    aiRelevance: 70,
    growthPotential: 75,
    marketOpportunity: 70,
    interestKeys: ["content", "ai"],
    nextStep: "Publish a short series of AI-assisted product videos as portfolio evidence.",
  },
  {
    id: "ai-visual",
    name: "AI × Visual",
    nameOriginal: "AI × 视觉",
    blurb: "Build on AI image generation and Photoshop toward commercial visual work.",
    coreSkills: ["AI Product Image Generation", "Photoshop"],
    transferableSkills: ["Listing Optimization", "Short Video Editing"],
    learnable: [
      "Advanced image workflows",
      "Brand-consistent art direction",
      "Model fine-tuning basics",
    ],
    aiRelevance: 80,
    growthPotential: 70,
    marketOpportunity: 65,
    interestKeys: ["visual", "ai"],
    nextStep: "Assemble 8-10 AI visual pieces with the prompt and process shown beside each.",
  },
  {
    id: "ai-operations",
    name: "AI × Operations",
    nameOriginal: "AI × 运营",
    blurb: "Apply automation and data monitoring to make operations teams faster.",
    coreSkills: [
      "E-commerce Operations",
      "Data Monitoring",
      "Inventory / Supply Chain Coordination",
    ],
    transferableSkills: ["Basic Programming", "Advertising Operations"],
    learnable: ["Workflow automation", "SQL / spreadsheets at scale", "Ops metrics design"],
    aiRelevance: 65,
    growthPotential: 70,
    marketOpportunity: 70,
    interestKeys: ["automation", "ai", "programming"],
    nextStep:
      "Automate one recurring report you used to build by hand and document the time saved.",
  },
  {
    id: "explore",
    name: "Explore / New Directions",
    nameOriginal: "探索新方向",
    blurb: "Deliberately unclear space kept open for tests that do not fit the other five.",
    coreSkills: [],
    transferableSkills: ["Overseas Market Research", "Data Monitoring"],
    learnable: ["Whatever the next experiment needs"],
    aiRelevance: 50,
    growthPotential: 60,
    marketOpportunity: 55,
    interestKeys: ["ai"],
    nextStep:
      "Pick one small paid or unpaid project outside your current lane and run it for two weeks.",
  },
];

export function getDirection(id?: string) {
  return careerDirections.find((d) => d.id === id);
}
