import type { Job } from "./types";

/** Original V1 mock listings. The demo persona that lived here was removed in
 * V1.1 — the authoritative profile is `defaultCareerProfile`. */
export const mockJobs: Job[] = [
  {
    id: "lumen-senior-product-designer",
    title: "Senior Product Designer",
    company: "Lumen Studio",
    location: "Lisbon, PT",
    workMode: "hybrid",
    salaryMin: 135000,
    salaryMax: 160000,
    skills: ["Figma", "Design Systems", "Design Ops", "Prototyping", "Team Leadership"],
    seniority: "senior",
    postedDaysAgo: 0,
    summary:
      "Own end-to-end design for Lumen's core workspace product, from research through shipped interface, alongside two other designers.",
    responsibilities: [
      "Lead design for the workspace surface and its component library",
      "Partner with engineering on a shared Figma-to-code system",
      "Run lightweight research cycles every sprint",
    ],
  },
  {
    id: "northwind-lead-ux-engineer",
    title: "Lead UX Engineer",
    company: "Northwind Labs",
    location: "Remote (EU)",
    workMode: "remote",
    salaryMin: 140000,
    salaryMax: 165000,
    skills: ["Figma", "Design Systems", "Prototyping", "Accessibility", "TypeScript"],
    seniority: "lead",
    postedDaysAgo: 1,
    summary:
      "Bridge design and front-end: build the production component library that the whole product org designs against.",
    responsibilities: [
      "Maintain the design system in both Figma and code",
      "Set accessibility standards across product surfaces",
      "Mentor two designers on systems thinking",
    ],
  },
  {
    id: "atlas-design-systems-lead",
    title: "Design Systems Lead",
    company: "Atlas & Co",
    location: "London, UK",
    workMode: "hybrid",
    salaryMin: 115000,
    salaryMax: 132000,
    skills: ["Design Systems", "Design Ops", "Figma", "Accessibility"],
    seniority: "lead",
    postedDaysAgo: 2,
    summary:
      "Consolidate four product design languages into one system, with a small platform team behind you.",
    responsibilities: [
      "Audit and unify existing component libraries",
      "Define contribution and governance model",
      "Publish documentation the whole org uses",
    ],
  },
  {
    id: "vela-principal-product-designer",
    title: "Principal Product Designer",
    company: "Vela",
    location: "Remote (Global)",
    workMode: "remote",
    salaryMin: 160000,
    salaryMax: 190000,
    skills: ["Product Strategy", "Design Systems", "User Research", "Team Leadership", "Figma"],
    seniority: "principal",
    postedDaysAgo: 1,
    summary:
      "Set the design direction for Vela's analytics platform and coach a team of five without managing them.",
    responsibilities: [
      "Own the multi-quarter design strategy",
      "Raise the craft bar through critique and pairing",
      "Partner directly with the founders on positioning",
    ],
  },
  {
    id: "halden-brand-systems-manager",
    title: "Brand Systems Manager",
    company: "Halden",
    location: "Copenhagen, DK",
    workMode: "onsite",
    salaryMin: 95000,
    salaryMax: 112000,
    skills: ["Design Systems", "Brand Design", "Figma"],
    seniority: "senior",
    postedDaysAgo: 4,
    summary: "Steward Halden's brand system across product, packaging and retail touchpoints.",
    responsibilities: [
      "Maintain brand guidelines and asset library",
      "Review work from external studios",
      "Keep product and brand visually aligned",
    ],
  },
  {
    id: "cobalt-head-of-design",
    title: "Head of Design",
    company: "Cobalt",
    location: "Remote (EU)",
    workMode: "remote",
    salaryMin: 150000,
    salaryMax: 175000,
    skills: ["Team Leadership", "Product Strategy", "Design Ops", "User Research"],
    seniority: "principal",
    postedDaysAgo: 3,
    summary:
      "Build and lead a four-person design function at a 60-person fintech, hands-on for the first two quarters.",
    responsibilities: [
      "Hire and grow the design team",
      "Own design operations and rituals",
      "Stay hands-on across the core money flows",
    ],
  },
  {
    id: "meridian-product-designer",
    title: "Product Designer, Growth",
    company: "Meridian",
    location: "Remote (EU)",
    workMode: "remote",
    salaryMin: 105000,
    salaryMax: 125000,
    skills: ["Figma", "Prototyping", "User Research", "Experimentation"],
    seniority: "mid",
    postedDaysAgo: 0,
    summary: "Design and ship experiments across onboarding, pricing and activation surfaces.",
    responsibilities: [
      "Run a weekly experiment cadence with growth engineering",
      "Design onboarding and paywall variants",
      "Report on qualitative signal from user sessions",
    ],
  },
  {
    id: "solace-senior-ux-researcher",
    title: "Senior Product Designer, Platform",
    company: "Solace Health",
    location: "Berlin, DE",
    workMode: "hybrid",
    salaryMin: 128000,
    salaryMax: 148000,
    skills: ["User Research", "Design Systems", "Accessibility", "Figma", "Prototyping"],
    seniority: "senior",
    postedDaysAgo: 2,
    summary:
      "Design clinical workflows where accessibility and error prevention matter more than novelty.",
    responsibilities: [
      "Design core clinician-facing workflows",
      "Meet WCAG 2.2 AA across all surfaces",
      "Validate designs with practising clinicians",
    ],
  },
  {
    id: "orbit-staff-designer",
    title: "Staff Product Designer",
    company: "Orbit",
    location: "Remote (Global)",
    workMode: "remote",
    salaryMin: 145000,
    salaryMax: 170000,
    skills: ["Design Systems", "Product Strategy", "Figma", "Prototyping", "Team Leadership"],
    seniority: "lead",
    postedDaysAgo: 1,
    summary:
      "Lead design on the developer platform: APIs, dashboards, and the docs experience around them.",
    responsibilities: [
      "Own the dashboard and API key surfaces",
      "Prototype in code alongside platform engineers",
      "Define the platform's interaction patterns",
    ],
  },
  {
    id: "kestrel-design-ops-lead",
    title: "Design Ops Lead",
    company: "Kestrel",
    location: "Amsterdam, NL",
    workMode: "hybrid",
    salaryMin: 118000,
    salaryMax: 140000,
    skills: ["Design Ops", "Design Systems", "Team Leadership", "Figma"],
    seniority: "lead",
    postedDaysAgo: 5,
    summary:
      "Make a 20-person design org faster: tooling, rituals, hiring loops and system governance.",
    responsibilities: [
      "Own tooling and file architecture",
      "Run the design hiring process",
      "Instrument design throughput and quality",
    ],
  },
  {
    id: "fathom-product-designer",
    title: "Product Designer",
    company: "Fathom",
    location: "Remote (EU)",
    workMode: "remote",
    salaryMin: 132000,
    salaryMax: 150000,
    skills: ["Figma", "Prototyping", "User Research", "Product Strategy"],
    seniority: "senior",
    postedDaysAgo: 0,
    summary:
      "Second designer at a research-tooling startup; you'll shape both the product and how design works here.",
    responsibilities: [
      "Design the core research workspace",
      "Set up the first component library",
      "Talk to users every week",
    ],
  },
  {
    id: "ridge-visual-designer",
    title: "Senior Visual Designer",
    company: "Ridge Interactive",
    location: "New York, US",
    workMode: "onsite",
    salaryMin: 108000,
    salaryMax: 126000,
    skills: ["Brand Design", "Motion Design", "Figma"],
    seniority: "senior",
    postedDaysAgo: 6,
    summary: "Craft campaign and product visuals for consumer clients in a studio environment.",
    responsibilities: [
      "Art-direct campaign work",
      "Produce motion and static assets",
      "Present concepts to clients",
    ],
  },
];

export function getJob(id: string): Job | undefined {
  return mockJobs.find((j) => j.id === id);
}
