/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DirectionsRouteImport } from './routes/directions'
import { Route as HiddenRouteImport } from './routes/hidden'
import { Route as ImportRouteImport } from './routes/import'
import { Route as MatchingRouteImport } from './routes/matching'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as TodayRouteImport } from './routes/today'
import { Route as ApiAnalyzeJobRouteImport } from './routes/api.analyze-job'
import { Route as ApiDiscover51jobRouteImport } from './routes/api.discover-51job'
import { Route as ApiDiscoverLiepinRouteImport } from './routes/api.discover-liepin'
import { Route as ApiImportJobUrlRouteImport } from './routes/api.import-job-url'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectionsRoute = DirectionsRouteImport.update({
  id: '/directions',
  path: '/directions',
  getParentRoute: () => rootRouteImport,
} as any)
const HiddenRoute = HiddenRouteImport.update({
  id: '/hidden',
  path: '/hidden',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchingRoute = MatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeJobRoute = ApiAnalyzeJobRouteImport.update({
  id: '/api/analyze-job',
  path: '/api/analyze-job',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscover51jobRoute = ApiDiscover51jobRouteImport.update({
  id: '/api/discover-51job',
  path: '/api/discover-51job',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscoverLiepinRoute = ApiDiscoverLiepinRouteImport.update({
  id: '/api/discover-liepin',
  path: '/api/discover-liepin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportJobUrlRoute = ApiImportJobUrlRouteImport.update({
  id: '/api/import-job-url',
  path: '/api/import-job-url',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/directions': typeof DirectionsRoute
  '/hidden': typeof HiddenRoute
  '/import': typeof ImportRoute
  '/matching': typeof MatchingRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/today': typeof TodayRoute
  '/api/analyze-job': typeof ApiAnalyzeJobRoute
  '/api/discover-51job': typeof ApiDiscover51jobRoute
  '/api/discover-liepin': typeof ApiDiscoverLiepinRoute
  '/api/import-job-url': typeof ApiImportJobUrlRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/directions': typeof DirectionsRoute
  '/hidden': typeof HiddenRoute
  '/import': typeof ImportRoute
  '/matching': typeof MatchingRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/today': typeof TodayRoute
  '/api/analyze-job': typeof ApiAnalyzeJobRoute
  '/api/discover-51job': typeof ApiDiscover51jobRoute
  '/api/discover-liepin': typeof ApiDiscoverLiepinRoute
  '/api/import-job-url': typeof ApiImportJobUrlRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/directions': typeof DirectionsRoute
  '/hidden': typeof HiddenRoute
  '/import': typeof ImportRoute
  '/matching': typeof MatchingRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/today': typeof TodayRoute
  '/api/analyze-job': typeof ApiAnalyzeJobRoute
  '/api/discover-51job': typeof ApiDiscover51jobRoute
  '/api/discover-liepin': typeof ApiDiscoverLiepinRoute
  '/api/import-job-url': typeof ApiImportJobUrlRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/auth'
    | '/directions'
    | '/hidden'
    | '/import'
    | '/matching'
    | '/onboarding'
    | '/profile'
    | '/saved'
    | '/today'
    | '/api/analyze-job'
    | '/api/discover-51job'
    | '/api/discover-liepin'
    | '/api/import-job-url'
    | '/jobs/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/auth'
    | '/directions'
    | '/hidden'
    | '/import'
    | '/matching'
    | '/onboarding'
    | '/profile'
    | '/saved'
    | '/today'
    | '/api/analyze-job'
    | '/api/discover-51job'
    | '/api/discover-liepin'
    | '/api/import-job-url'
    | '/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/auth'
    | '/directions'
    | '/hidden'
    | '/import'
    | '/matching'
    | '/onboarding'
    | '/profile'
    | '/saved'
    | '/today'
    | '/api/analyze-job'
    | '/api/discover-51job'
    | '/api/discover-liepin'
    | '/api/import-job-url'
    | '/jobs/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AuthRoute: typeof AuthRoute
  DirectionsRoute: typeof DirectionsRoute
  HiddenRoute: typeof HiddenRoute
  ImportRoute: typeof ImportRoute
  MatchingRoute: typeof MatchingRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  SavedRoute: typeof SavedRoute
  TodayRoute: typeof TodayRoute
  ApiAnalyzeJobRoute: typeof ApiAnalyzeJobRoute
  ApiDiscover51jobRoute: typeof ApiDiscover51jobRoute
  ApiDiscoverLiepinRoute: typeof ApiDiscoverLiepinRoute
  ApiImportJobUrlRoute: typeof ApiImportJobUrlRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directions': {
      id: '/directions'
      path: '/directions'
      fullPath: '/directions'
      preLoaderRoute: typeof DirectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hidden': {
      id: '/hidden'
      path: '/hidden'
      fullPath: '/hidden'
      preLoaderRoute: typeof HiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matching': {
      id: '/matching'
      path: '/matching'
      fullPath: '/matching'
      preLoaderRoute: typeof MatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-job': {
      id: '/api/analyze-job'
      path: '/api/analyze-job'
      fullPath: '/api/analyze-job'
      preLoaderRoute: typeof ApiAnalyzeJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discover-51job': {
      id: '/api/discover-51job'
      path: '/api/discover-51job'
      fullPath: '/api/discover-51job'
      preLoaderRoute: typeof ApiDiscover51jobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discover-liepin': {
      id: '/api/discover-liepin'
      path: '/api/discover-liepin'
      fullPath: '/api/discover-liepin'
      preLoaderRoute: typeof ApiDiscoverLiepinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import-job-url': {
      id: '/api/import-job-url'
      path: '/api/import-job-url'
      fullPath: '/api/import-job-url'
      preLoaderRoute: typeof ApiImportJobUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AuthRoute: AuthRoute,
  DirectionsRoute: DirectionsRoute,
  HiddenRoute: HiddenRoute,
  ImportRoute: ImportRoute,
  MatchingRoute: MatchingRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  SavedRoute: SavedRoute,
  TodayRoute: TodayRoute,
  ApiAnalyzeJobRoute: ApiAnalyzeJobRoute,
  ApiDiscover51jobRoute: ApiDiscover51jobRoute,
  ApiDiscoverLiepinRoute: ApiDiscoverLiepinRoute,
  ApiImportJobUrlRoute: ApiImportJobUrlRoute,
  JobsJobIdRoute: JobsJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
